### ISSUE TITLE
caret position when text > input width

### ISSUE THREAD

**Issue by DjLeChuck** [azerion/phaser-input#63]
Hi,

When the text of an input is greater than its width, the caret is blocked to the right even if we move backward with <kbd>Begin</kbd> or <kbd>←</kbd>. However, the "real" caret continues to move in it's DOM input  and when we type, the text is displayed to the right position, but we don't see it if it's to the left of the field for example.

The `InputField.prototype.updateCursor` seems to be the bad guy if I understand it correctly ([source here](https://github.com/orange-games/phaser-input/blob/master/build/phaser-input.js#L438-L452)).

It's a bug, isn't it?

**Comment by JonGardner-RedSpace** [comment]
I'm hitting the same problem, wondering if any progress has been made on this issue?
